### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by pinsily** [huobiapi/huobi_Python#2]
hello, I cloned this project and learned huobi api last night

and then i found one bug in this

1. huobi/impl/restapirequestimpl.py

```python
    def get_exchange_timestamp(self):
        request = self.__create_request_by_get("/v1/common/timestamp")

        def parse(json):
            return convert_cst_in_millisecond_to_utc(json["data"])

        request.json_parser = parse
        return request
```

In parse function, it is param json is a JsonWrapper instance but not dict

so it should be corrected as:

```python
def parse(json):
    return convert_cst_in_millisecond_to_utc(json.get_int("data"))
``` 

sorry to interrupt you all

**Comment by macomfan** [comment]
Thank you for your feedback.
Exactly, this should be a bug, I have fixed it and uploaded it. Please check again.
Your comment is welcome.

Thanks,
Best regards
