### ISSUE TITLE
get_order error

### ISSUE THREAD

**Issue by vesslanjin** [huobiapi/huobi_Python#3]
have made a simple test, but get_order had error.  would you pls have a look at it ? 

from huobi import RequestClient
from huobi.model import *
import time
request_client = RequestClient(api_key="xxx",  secret_key="xxx")
theid = request_client.create_order("etcusdt", AccountType.SPOT, OrderType.SELL_LIMIT, 0.1, 6.2)
print(theid)
od = request_client.get_order( "etcusdt", theid)
print(od)
request_client.cancel_order("etcusdt", theid)

have an error: huobi.exception.huobiapiexception.HuobiApiException: ('ExecuteError', '[Executing] validation-format-error: Format Error: order-id.')

**Comment by macomfan** [comment]
Thanks for your feedback, it is fixed. please check again.
Best regards

**Comment by vesslanjin** [comment]
thanks
