### ISSUE TITLE
Account.get_balance error  in  account.py

### ISSUE THREAD

**Issue by vesslanjin** [huobiapi/huobi_Python#4]
from huobi import RequestClient
from huobi.model import *
import time
request_client = RequestClient(api_key="...", secret_key="...")
balance = request_client.get_account_balance_by_account_type(AccountType.SPOT)
print(type(balance))
btc_amount = balance.get_balance("btc")
print(btc_amount)

command line output: 
<class 'huobi.model.account.Account'>
Traceback (most recent call last):
  File "test_get_balance.py", line 11, in <module>
    btc_amount = balance.get_balance("btc")
  File "/usr/local/pypy3/site-packages/huobi_client-0.1-py3.6.egg/huobi/model/account.py", line 30, in get_balance
    for balance in self.balances:
TypeError: 'RestApiRequest' object is not iterable

**Comment by macomfan** [comment]
Thanks for your report, I modified the code, it should be fixed, but i have not tested this modification due to the network issue. I will test in next week.
Thanks,
Best regards,

**Comment by vesslanjin** [comment]
does this veriosn have any special depend on g++ version ?  on my centos 7.5.1804, I successfully get a libHuobiClient.a, but when I tried to compile the example, it failed with below message: 

ClientCreator.cpp:(.text+0xabc): undefined reference to `std::regex_token_iterator<char const*, char, std::regex_traits<char> >::regex_token_iterator(char const*, char const*, std::basic_regex<char, std::regex_traits<char> > const&, int, std::bitset<11ul>)'
ClientCreator.cpp:(.text+0xac9): undefined reference to `std::regex_token_iterator<char const*, char, std::regex_traits<char> >::regex_token_iterator()'

it seems my g++ doesn't support regex stuff, and I added -std=c++11  option already 

the g++ version I have is gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
